site_name: Sed HOWTO
site_author: 'tomazmcn@gmail.com'
site_description: 'Versão em Markdown e HTML do documento Sed HOWTO.'
repo_url: https://github.com/tomazcunha/sed-howto-mkdocs
# copyright: ''
# repo_name: 'GitHub'
# edit_uri: tree/master/docs

# cria links que apontam diretamente para o arquivo de destino em vez do diretório de destino.
use_directory_urls: false

nav:
    - 0. Versão Markdown com MkDocs: 'index.md'
    - 1. Sobre este documento: 'Cap01-Sobre.md'
    - 2. Conhecendo o sed: 'Cap02-Conhecendo-o-sed.md'
    - 3. Perdendo o medo do sed: 'Cap03-Perdendo-o-medo-do-sed.md'
    - 4. Os comandos do sed: 'Cap04-Os-comandos-do-sed.md'
    - 5. Conceitos básicos: 'Cap05-Conceitos-básicos.md'
    - 6. Conceitos complementares: 'Cap06-Conceitos-complementares.md'
    - 7. Tarefas diversas: 'Cap07-Tarefas-diversas.md'
    - 8. Conceitos avançados: 'Cap08-Conceitos-avançados.md'
    - 9. Fluxogramas: 'Cap09-Fluxogramas.md'
    - 10. Nota sobre os adicionais GNU: 'Cap10-Nota-sobre-os-adicionais-GNU.md'
    - 11. Onde obter mais informações: 'Cap11-Onde-obter-mais-informações.md'

theme:
    # name: readthedocs
    # highlightjs: true
    # hljs_languages:
    #     - shell
    #     - bash
        # - Shell Session

    name: material

    # name: windmill
    # name: readthedocs

    # name: cinder      # problema com menu
    # name: bootstrap   # problema com menu
    # name: bootstrap4
    # name: gitbook       # não funciona
    # name: alabaster   # não funciona

    # name: mkdocs
    # highlightjs: true
    # hljs_languages:
    #     - python
    # # hljs_style: github

    # palette:
    #     primary: 'blue grey'
    #     accent: 'indigo'

    font:
        text: 'Roboto'
        # text: 'Roboto Slab'
        # text: 'Ubuntu'
        # text: 'Ubuntu Mono'
        # text: 'Open Sans'
        # text: 'Lato'
        # text: 'Montserrat'
        # text: 'Source Sans Pro'
        # text: 'Merriweather'
        # text: 'PT Serif'
        # text: 'PT Sans'
        # text: 'Inconsolata'
        # text: 'Quicksand'
        # text: 'Work Sans'
        # text: 'Crimson Text'
        # text: 'Oxygen'
        # text: 'Pacifico'
        # text: 'Rubik'

        code: 'Inconsolata'
        # code: 'Roboto Slab'
        # code: 'Roboto'
        # code: 'Ubuntu Mono'
        # code: 'Open Sans'
        # code: 'Lato'

    language: 'pt'
    favicon: assets/img/favicon.ico
    # feature:
    #     tabs: true
# extra:
#     manifest: 'manifest.webmanifest'
#     social:
#         - type: 'github'
#           link: 'https://github.com/squidfunk'
#         - type: 'twitter'
#           link: 'https://twitter.com/squidfunk'
#         - type: 'linkedin'
#           link: 'https://linkedin.com/in/squidfunk'

extra_css:
    # - assets/stylesheets/extra-readthedocs.css
    - assets/stylesheets/extra-material.css
    - assets/stylesheets/a11y-dark.css

extra_javascript:
    - assets/javascript/highlight.pack.js
    - assets/javascript/hljs.js


    # - assets/stylesheets/atelier-dune-dark.css
    # - assets/stylesheets/an-old-hope.css
    # - assets/stylesheets/agate.css
    # - assets/stylesheets/atom-one-dark.css
    # - assets/stylesheets/darkula.css
    # - assets/stylesheets/dracula.css
    # - assets/stylesheets/hopscotch.css
    # - assets/stylesheets/solarized-dark.css


# google_analytics:
#   - 'UA-XXXXXXXX-X'
#   - 'auto'
    # name: readthedocs
    # name: bootstrap
    # name: bootstrap4
    # name: windmill
    # name: cinder
    # name: alabaster   # nao está fuincionando, mesmo instalado
    # name: cluster       # não fuinciona as configurações
# site_favicon: 'img/favicon.ico' # nao precisa configurar favicon se estiver em docs
# suppress_nextprev: true
# suppress_nextprev: false



# markdown_extensions:
#     - pymdownx.arithmatex
#     - pymdownx.betterem:
#         smart_enable: all
#     - pymdownx.caret
#     - pymdownx.critic
#     - pymdownx.details
#     - pymdownx.emoji:
#         emoji_generator: !!python/name:pymdownx.emoji.to_svg
#     - pymdownx.inlinehilite
#     - pymdownx.magiclink
#     - pymdownx.mark
#     - pymdownx.smartsymbols
#     - pymdownx.superfences
#     - pymdownx.tasklist:
#         custom_checkbox: true
#     - pymdownx.tilde

    # - codehilite:
    #     linenums: true

    # - fenced_code
    # - toc:
    #     permalink: True
